sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - BROWSERSTACK_USERNAME: dylanschiemann2
  - BROWSERSTACK_ACCESS_KEY: 2upt88qsxsqqeukQvecu
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt dev
- grunt intern:browserstack --test-reporter
- grunt uploadCoverage
