export const root: string;
export const scroll: string;
export const label: string;
export const labelName: string;
export const content: string;
export const hasChildren: string;
export const expanded: string;
export const row: string;
export const selected: string;
